title: Translate Toolkit
description: Tools and Python APIs for translation and localization engineering.
url: https://toolkit.translatehouse.org
baseurl: ""
repository: translate/translate

markdown: kramdown

exclude:
- requirements
