# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unknown'
#
# Created: Mon Nov 13 16:15:57 2006
#      by: PyQt4 UI code generator 4.0
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt4 import QtCore, QtGui

class Ui_frmPreference(object):
    def setupUi(self, frmPreference):
        frmPreference.setObjectName("frmPreference")
        frmPreference.resize(QtCore.QSize(QtCore.QRect(0,0,485,376).size()).expandedTo(frmPreference.minimumSizeHint()))

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPreference.sizePolicy().hasHeightForWidth())
        frmPreference.setSizePolicy(sizePolicy)

        self.gridlayout = QtGui.QGridLayout(frmPreference)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")

        self.tabWidget = QtGui.QTabWidget(frmPreference)
        self.tabWidget.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.tabWidget.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")

        self.tab1 = QtGui.QWidget()
        self.tab1.setEnabled(True)
        self.tab1.setObjectName("tab1")

        self.gridlayout1 = QtGui.QGridLayout(self.tab1)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")

        self.frame2 = QtGui.QFrame(self.tab1)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2.setObjectName("frame2")

        self.gridlayout2 = QtGui.QGridLayout(self.frame2)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")

        self.label = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridlayout2.addWidget(self.label,0,0,1,1)

        self.spinBox = QtGui.QSpinBox(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName("spinBox")
        self.gridlayout2.addWidget(self.spinBox,0,1,1,1)
        self.gridlayout1.addWidget(self.frame2,1,0,1,1)

        self.frame = QtGui.QFrame(self.tab1)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFocusPolicy(QtCore.Qt.TabFocus)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.gridlayout3 = QtGui.QGridLayout(self.frame)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")

        self.label5 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setObjectName("label5")
        self.gridlayout3.addWidget(self.label5,3,0,1,1)

        self.cbxLanguageCode = QtGui.QComboBox(self.frame)
        self.cbxLanguageCode.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxLanguageCode.sizePolicy().hasHeightForWidth())
        self.cbxLanguageCode.setSizePolicy(sizePolicy)
        self.cbxLanguageCode.setAcceptDrops(False)
        self.cbxLanguageCode.setEditable(True)
        self.cbxLanguageCode.setObjectName("cbxLanguageCode")
        self.gridlayout3.addWidget(self.cbxLanguageCode,2,3,1,1)

        self.label6 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6.sizePolicy().hasHeightForWidth())
        self.label6.setSizePolicy(sizePolicy)
        self.label6.setObjectName("label6")
        self.gridlayout3.addWidget(self.label6,4,0,1,1)

        self.cbxFullLanguage = QtGui.QComboBox(self.frame)
        self.cbxFullLanguage.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxFullLanguage.sizePolicy().hasHeightForWidth())
        self.cbxFullLanguage.setSizePolicy(sizePolicy)
        self.cbxFullLanguage.setEditable(True)
        self.cbxFullLanguage.setObjectName("cbxFullLanguage")
        self.gridlayout3.addWidget(self.cbxFullLanguage,2,1,1,1)

        self.cbxTimeZone = QtGui.QComboBox(self.frame)
        self.cbxTimeZone.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxTimeZone.sizePolicy().hasHeightForWidth())
        self.cbxTimeZone.setSizePolicy(sizePolicy)
        self.cbxTimeZone.setEditable(True)
        self.cbxTimeZone.setObjectName("cbxTimeZone")
        self.gridlayout3.addWidget(self.cbxTimeZone,4,1,1,3)

        self.label1 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setObjectName("label1")
        self.gridlayout3.addWidget(self.label1,0,0,1,1)

        self.label3 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setObjectName("label3")
        self.gridlayout3.addWidget(self.label3,2,0,1,1)

        self.label2 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setObjectName("label2")
        self.gridlayout3.addWidget(self.label2,1,0,1,1)

        self.label4 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4.sizePolicy().hasHeightForWidth())
        self.label4.setSizePolicy(sizePolicy)
        self.label4.setObjectName("label4")
        self.gridlayout3.addWidget(self.label4,2,2,1,1)

        self.UserName = QtGui.QLineEdit(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserName.sizePolicy().hasHeightForWidth())
        self.UserName.setSizePolicy(sizePolicy)
        self.UserName.setMaxLength(32768)
        self.UserName.setObjectName("UserName")
        self.gridlayout3.addWidget(self.UserName,0,1,1,3)

        self.EmailAddress = QtGui.QLineEdit(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmailAddress.sizePolicy().hasHeightForWidth())
        self.EmailAddress.setSizePolicy(sizePolicy)
        self.EmailAddress.setObjectName("EmailAddress")
        self.gridlayout3.addWidget(self.EmailAddress,1,1,1,3)

        self.SupportTeam = QtGui.QLineEdit(self.frame)
        self.SupportTeam.setObjectName("SupportTeam")
        self.gridlayout3.addWidget(self.SupportTeam,3,1,1,3)
        self.gridlayout1.addWidget(self.frame,0,0,1,1)

        self.chkHeaderAuto = QtGui.QCheckBox(self.tab1)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkHeaderAuto.sizePolicy().hasHeightForWidth())
        self.chkHeaderAuto.setSizePolicy(sizePolicy)
        self.chkHeaderAuto.setObjectName("chkHeaderAuto")
        self.gridlayout1.addWidget(self.chkHeaderAuto,2,0,1,1)

        spacerItem = QtGui.QSpacerItem(20,10,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout1.addItem(spacerItem,3,0,1,1)
        self.tabWidget.addTab(self.tab1, "")

        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")

        self.gridlayout4 = QtGui.QGridLayout(self.tab2)
        self.gridlayout4.setMargin(9)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")

        self.bntDefaults = QtGui.QPushButton(self.tab2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntDefaults.sizePolicy().hasHeightForWidth())
        self.bntDefaults.setSizePolicy(sizePolicy)
        self.bntDefaults.setObjectName("bntDefaults")
        self.gridlayout4.addWidget(self.bntDefaults,1,0,1,1)

        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout4.addItem(spacerItem1,2,0,1,1)

        self.frame21 = QtGui.QFrame(self.tab2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame21.sizePolicy().hasHeightForWidth())
        self.frame21.setSizePolicy(sizePolicy)
        self.frame21.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame21.setFrameShadow(QtGui.QFrame.Raised)
        self.frame21.setObjectName("frame21")

        self.gridlayout5 = QtGui.QGridLayout(self.frame21)
        self.gridlayout5.setMargin(9)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")

        self.lblsupportteam = QtGui.QLabel(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblsupportteam.sizePolicy().hasHeightForWidth())
        self.lblsupportteam.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblsupportteam.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblsupportteam.setFont(font)
        self.lblsupportteam.setObjectName("lblsupportteam")
        self.gridlayout5.addWidget(self.lblsupportteam,3,0,1,1)

        self.label41 = QtGui.QLabel(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label41.sizePolicy().hasHeightForWidth())
        self.label41.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label41.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label41.setFont(font)
        self.label41.setObjectName("label41")
        self.gridlayout5.addWidget(self.label41,2,0,1,1)

        self.Source = QtGui.QLabel(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Source.sizePolicy().hasHeightForWidth())
        self.Source.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.Source.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.Source.setFont(font)
        self.Source.setObjectName("Source")
        self.gridlayout5.addWidget(self.Source,1,0,1,1)

        self.label21 = QtGui.QLabel(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label21.sizePolicy().hasHeightForWidth())
        self.label21.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label21.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label21.setFont(font)
        self.label21.setScaledContents(True)
        self.label21.setWordWrap(True)
        self.label21.setIndent(0)
        self.label21.setObjectName("label21")
        self.gridlayout5.addWidget(self.label21,0,0,1,1)

        self.bntComment = QtGui.QPushButton(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntComment.sizePolicy().hasHeightForWidth())
        self.bntComment.setSizePolicy(sizePolicy)
        self.bntComment.setObjectName("bntComment")
        self.gridlayout5.addWidget(self.bntComment,3,2,1,1)

        self.bntTarget = QtGui.QPushButton(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntTarget.sizePolicy().hasHeightForWidth())
        self.bntTarget.setSizePolicy(sizePolicy)
        self.bntTarget.setObjectName("bntTarget")
        self.gridlayout5.addWidget(self.bntTarget,2,2,1,1)

        self.bntSource = QtGui.QPushButton(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntSource.sizePolicy().hasHeightForWidth())
        self.bntSource.setSizePolicy(sizePolicy)
        self.bntSource.setObjectName("bntSource")
        self.gridlayout5.addWidget(self.bntSource,1,2,1,1)

        self.bntOverview = QtGui.QPushButton(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntOverview.sizePolicy().hasHeightForWidth())
        self.bntOverview.setSizePolicy(sizePolicy)
        self.bntOverview.setObjectName("bntOverview")
        self.gridlayout5.addWidget(self.bntOverview,0,2,1,1)

        self.lblComment = QtGui.QLabel(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblComment.sizePolicy().hasHeightForWidth())
        self.lblComment.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblComment.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblComment.setFont(font)
        self.lblComment.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblComment.setObjectName("lblComment")
        self.gridlayout5.addWidget(self.lblComment,3,1,1,1)

        self.lblTarget = QtGui.QLabel(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTarget.sizePolicy().hasHeightForWidth())
        self.lblTarget.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblTarget.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblTarget.setFont(font)
        self.lblTarget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTarget.setObjectName("lblTarget")
        self.gridlayout5.addWidget(self.lblTarget,2,1,1,1)

        self.lblSource = QtGui.QLabel(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSource.sizePolicy().hasHeightForWidth())
        self.lblSource.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblSource.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblSource.setFont(font)
        self.lblSource.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSource.setObjectName("lblSource")
        self.gridlayout5.addWidget(self.lblSource,1,1,1,1)

        self.lblOverView = QtGui.QLabel(self.frame21)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOverView.sizePolicy().hasHeightForWidth())
        self.lblOverView.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblOverView.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblOverView.setFont(font)
        self.lblOverView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOverView.setObjectName("lblOverView")
        self.gridlayout5.addWidget(self.lblOverView,0,1,1,1)
        self.gridlayout4.addWidget(self.frame21,0,0,1,1)
        self.tabWidget.addTab(self.tab2, "")
        self.gridlayout.addWidget(self.tabWidget,0,0,1,1)

        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(5)
        self.hboxlayout.setObjectName("hboxlayout")

        spacerItem2 = QtGui.QSpacerItem(285,31,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)

        self.okButton = QtGui.QPushButton(frmPreference)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(1),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)

        self.cancelButton = QtGui.QPushButton(frmPreference)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.gridlayout.addLayout(self.hboxlayout,1,0,1,1)

        self.retranslateUi(frmPreference)
        self.cbxFullLanguage.setCurrentIndex(-1)
        QtCore.QObject.connect(self.cancelButton,QtCore.SIGNAL("clicked()"),frmPreference.reject)
        QtCore.QObject.connect(self.okButton,QtCore.SIGNAL("clicked()"),frmPreference.accept)
        QtCore.QMetaObject.connectSlotsByName(frmPreference)
        frmPreference.setTabOrder(self.cbxFullLanguage,self.cbxLanguageCode)
        frmPreference.setTabOrder(self.cbxLanguageCode,self.cbxTimeZone)
        frmPreference.setTabOrder(self.cbxTimeZone,self.spinBox)
        frmPreference.setTabOrder(self.spinBox,self.okButton)
        frmPreference.setTabOrder(self.okButton,self.cancelButton)
        frmPreference.setTabOrder(self.cancelButton,self.tabWidget)
        frmPreference.setTabOrder(self.tabWidget,self.bntComment)
        frmPreference.setTabOrder(self.bntComment,self.bntTarget)
        frmPreference.setTabOrder(self.bntTarget,self.bntSource)
        frmPreference.setTabOrder(self.bntSource,self.bntDefaults)
        frmPreference.setTabOrder(self.bntDefaults,self.bntOverview)

    def tr(self, string):
        return QtGui.QApplication.translate("frmPreference", string, None, QtGui.QApplication.UnicodeUTF8)

    def retranslateUi(self, frmPreference):
        frmPreference.setWindowTitle(self.tr("Preference"))
        self.label.setText(self.tr("Number of singular/plural forms"))
        self.label5.setText(self.tr("Support Team"))
        self.label6.setText(self.tr("Time Zone"))
        self.label1.setText(self.tr("UserName"))
        self.label3.setText(self.tr("Full Language Name"))
        self.label2.setText(self.tr("Email address"))
        self.label4.setText(self.tr("Language Code"))
        self.chkHeaderAuto.setText(self.tr("Automatically update header on save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), self.tr("Personalize"))
        self.bntDefaults.setText(self.tr("Defaults"))
        self.lblsupportteam.setText(self.tr("Comment"))
        self.label41.setText(self.tr("Target"))
        self.Source.setText(self.tr("Source"))
        self.label21.setText(self.tr("Overview"))
        self.bntComment.setText(self.tr("Choose"))
        self.bntTarget.setText(self.tr("Choose"))
        self.bntSource.setText(self.tr("Choose"))
        self.bntOverview.setText(self.tr("Choose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), self.tr("Font"))
        self.okButton.setText(self.tr("OK"))
        self.cancelButton.setText(self.tr("Cancel"))


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    frmPreference = QtGui.QDialog()
    ui = Ui_frmPreference()
    ui.setupUi(frmPreference)
    frmPreference.show()
    sys.exit(app.exec_())
