#!/usr/bin/env python
# 
# Copyright 2009 Mozilla Corporation, Zuza Software Foundation
# 
# This file is part of translate.
#
# translate is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""simple script to convert a PHP style .po file to a Python style .po file.  The manual 
(http://www.gnu.org/software/gettext/manual/gettext.html) explains the differences, but it's mainly 
substitution style. """

from translate.convert import phppo2pypo

if __name__ == '__main__':
    phppo2pypo.main()

