# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unknown'
#
# Created: Wed Jan  3 14:50:47 2007
#      by: PyQt4 UI code generator 4.0
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt4 import QtCore, QtGui

class Ui_frmPreference(object):
    def setupUi(self, frmPreference):
        frmPreference.setObjectName("frmPreference")
        frmPreference.resize(QtCore.QSize(QtCore.QRect(0,0,485,376).size()).expandedTo(frmPreference.minimumSizeHint()))

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPreference.sizePolicy().hasHeightForWidth())
        frmPreference.setSizePolicy(sizePolicy)

        self.gridlayout = QtGui.QGridLayout(frmPreference)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")

        self.tabWidget = QtGui.QTabWidget(frmPreference)
        self.tabWidget.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.tabWidget.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")

        self.tab1 = QtGui.QWidget()
        self.tab1.setEnabled(True)
        self.tab1.setObjectName("tab1")

        self.gridlayout1 = QtGui.QGridLayout(self.tab1)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")

        self.frame = QtGui.QFrame(self.tab1)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.gridlayout2 = QtGui.QGridLayout(self.frame)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")

        self.label5 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setObjectName("label5")
        self.gridlayout2.addWidget(self.label5,3,0,1,1)

        self.cbxLanguageCode = QtGui.QComboBox(self.frame)
        self.cbxLanguageCode.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxLanguageCode.sizePolicy().hasHeightForWidth())
        self.cbxLanguageCode.setSizePolicy(sizePolicy)
        self.cbxLanguageCode.setAcceptDrops(False)
        self.cbxLanguageCode.setEditable(True)
        self.cbxLanguageCode.setObjectName("cbxLanguageCode")
        self.gridlayout2.addWidget(self.cbxLanguageCode,2,3,1,1)

        self.label6 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6.sizePolicy().hasHeightForWidth())
        self.label6.setSizePolicy(sizePolicy)
        self.label6.setObjectName("label6")
        self.gridlayout2.addWidget(self.label6,4,0,1,1)

        self.cbxFullLanguage = QtGui.QComboBox(self.frame)
        self.cbxFullLanguage.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxFullLanguage.sizePolicy().hasHeightForWidth())
        self.cbxFullLanguage.setSizePolicy(sizePolicy)
        self.cbxFullLanguage.setEditable(True)
        self.cbxFullLanguage.setObjectName("cbxFullLanguage")
        self.gridlayout2.addWidget(self.cbxFullLanguage,2,1,1,1)

        self.cbxTimeZone = QtGui.QComboBox(self.frame)
        self.cbxTimeZone.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxTimeZone.sizePolicy().hasHeightForWidth())
        self.cbxTimeZone.setSizePolicy(sizePolicy)
        self.cbxTimeZone.setEditable(True)
        self.cbxTimeZone.setObjectName("cbxTimeZone")
        self.gridlayout2.addWidget(self.cbxTimeZone,4,1,1,3)

        self.label1 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setObjectName("label1")
        self.gridlayout2.addWidget(self.label1,0,0,1,1)

        self.label3 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setObjectName("label3")
        self.gridlayout2.addWidget(self.label3,2,0,1,1)

        self.label2 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setObjectName("label2")
        self.gridlayout2.addWidget(self.label2,1,0,1,1)

        self.label4 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4.sizePolicy().hasHeightForWidth())
        self.label4.setSizePolicy(sizePolicy)
        self.label4.setObjectName("label4")
        self.gridlayout2.addWidget(self.label4,2,2,1,1)

        self.UserName = QtGui.QLineEdit(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserName.sizePolicy().hasHeightForWidth())
        self.UserName.setSizePolicy(sizePolicy)
        self.UserName.setMaxLength(32768)
        self.UserName.setObjectName("UserName")
        self.gridlayout2.addWidget(self.UserName,0,1,1,3)

        self.EmailAddress = QtGui.QLineEdit(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmailAddress.sizePolicy().hasHeightForWidth())
        self.EmailAddress.setSizePolicy(sizePolicy)
        self.EmailAddress.setObjectName("EmailAddress")
        self.gridlayout2.addWidget(self.EmailAddress,1,1,1,3)

        self.SupportTeam = QtGui.QLineEdit(self.frame)
        self.SupportTeam.setObjectName("SupportTeam")
        self.gridlayout2.addWidget(self.SupportTeam,3,1,1,3)
        self.gridlayout1.addWidget(self.frame,0,0,1,1)

        self.chkHeaderAuto = QtGui.QCheckBox(self.tab1)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkHeaderAuto.sizePolicy().hasHeightForWidth())
        self.chkHeaderAuto.setSizePolicy(sizePolicy)
        self.chkHeaderAuto.setChecked(True)
        self.chkHeaderAuto.setObjectName("chkHeaderAuto")
        self.gridlayout1.addWidget(self.chkHeaderAuto,2,0,1,1)

        spacerItem = QtGui.QSpacerItem(20,10,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout1.addItem(spacerItem,3,0,1,1)
        self.tabWidget.addTab(self.tab1, "")

        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")

        self.gridlayout3 = QtGui.QGridLayout(self.tab2)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")

        self.bntDefaults = QtGui.QPushButton(self.tab2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntDefaults.sizePolicy().hasHeightForWidth())
        self.bntDefaults.setSizePolicy(sizePolicy)
        self.bntDefaults.setObjectName("bntDefaults")
        self.gridlayout3.addWidget(self.bntDefaults,1,0,1,1)

        self.frame2 = QtGui.QFrame(self.tab2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2.setObjectName("frame2")

        self.gridlayout4 = QtGui.QGridLayout(self.frame2)
        self.gridlayout4.setMargin(9)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")

        self.lblOverViewHeader = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOverViewHeader.sizePolicy().hasHeightForWidth())
        self.lblOverViewHeader.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblOverViewHeader.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblOverViewHeader.setFont(font)
        self.lblOverViewHeader.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOverViewHeader.setObjectName("lblOverViewHeader")
        self.gridlayout4.addWidget(self.lblOverViewHeader,1,1,1,1)

        self.Source = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Source.sizePolicy().hasHeightForWidth())
        self.Source.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.Source.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.Source.setFont(font)
        self.Source.setObjectName("Source")
        self.gridlayout4.addWidget(self.Source,2,0,1,1)

        self.bntComment = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntComment.sizePolicy().hasHeightForWidth())
        self.bntComment.setSizePolicy(sizePolicy)
        self.bntComment.setObjectName("bntComment")
        self.gridlayout4.addWidget(self.bntComment,4,2,1,1)

        self.bntTarget = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntTarget.sizePolicy().hasHeightForWidth())
        self.bntTarget.setSizePolicy(sizePolicy)
        self.bntTarget.setObjectName("bntTarget")
        self.gridlayout4.addWidget(self.bntTarget,3,2,1,1)

        self.bntSource = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntSource.sizePolicy().hasHeightForWidth())
        self.bntSource.setSizePolicy(sizePolicy)
        self.bntSource.setObjectName("bntSource")
        self.gridlayout4.addWidget(self.bntSource,2,2,1,1)

        self.lblSource = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSource.sizePolicy().hasHeightForWidth())
        self.lblSource.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblSource.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblSource.setFont(font)
        self.lblSource.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSource.setObjectName("lblSource")
        self.gridlayout4.addWidget(self.lblSource,2,1,1,1)

        self.lblComment = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblComment.sizePolicy().hasHeightForWidth())
        self.lblComment.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblComment.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblComment.setFont(font)
        self.lblComment.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblComment.setObjectName("lblComment")
        self.gridlayout4.addWidget(self.lblComment,4,1,1,1)

        self.lblsupportteam = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblsupportteam.sizePolicy().hasHeightForWidth())
        self.lblsupportteam.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblsupportteam.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblsupportteam.setFont(font)
        self.lblsupportteam.setObjectName("lblsupportteam")
        self.gridlayout4.addWidget(self.lblsupportteam,4,0,1,1)

        self.label41 = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label41.sizePolicy().hasHeightForWidth())
        self.label41.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label41.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label41.setFont(font)
        self.label41.setObjectName("label41")
        self.gridlayout4.addWidget(self.label41,3,0,1,1)

        self.lblTarget = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTarget.sizePolicy().hasHeightForWidth())
        self.lblTarget.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblTarget.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblTarget.setFont(font)
        self.lblTarget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTarget.setObjectName("lblTarget")
        self.gridlayout4.addWidget(self.lblTarget,3,1,1,1)

        self.bntOverview = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntOverview.sizePolicy().hasHeightForWidth())
        self.bntOverview.setSizePolicy(sizePolicy)
        self.bntOverview.setObjectName("bntOverview")
        self.gridlayout4.addWidget(self.bntOverview,0,2,1,1)

        self.lblOverView = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOverView.sizePolicy().hasHeightForWidth())
        self.lblOverView.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblOverView.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblOverView.setFont(font)
        self.lblOverView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOverView.setObjectName("lblOverView")
        self.gridlayout4.addWidget(self.lblOverView,0,1,1,1)

        self.label21 = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label21.sizePolicy().hasHeightForWidth())
        self.label21.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label21.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label21.setFont(font)
        self.label21.setScaledContents(True)
        self.label21.setWordWrap(True)
        self.label21.setIndent(0)
        self.label21.setObjectName("label21")
        self.gridlayout4.addWidget(self.label21,0,0,1,1)

        self.label2_2 = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_2.sizePolicy().hasHeightForWidth())
        self.label2_2.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label2_2.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label2_2.setFont(font)
        self.label2_2.setScaledContents(True)
        self.label2_2.setWordWrap(True)
        self.label2_2.setIndent(0)
        self.label2_2.setObjectName("label2_2")
        self.gridlayout4.addWidget(self.label2_2,1,0,1,1)

        self.bntOverviewHeader = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntOverviewHeader.sizePolicy().hasHeightForWidth())
        self.bntOverviewHeader.setSizePolicy(sizePolicy)
        self.bntOverviewHeader.setObjectName("bntOverviewHeader")
        self.gridlayout4.addWidget(self.bntOverviewHeader,1,2,1,1)
        self.gridlayout3.addWidget(self.frame2,0,0,1,1)

        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout3.addItem(spacerItem1,2,0,1,1)
        self.tabWidget.addTab(self.tab2, "")

        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")

        self.gridlayout5 = QtGui.QGridLayout(self.tab)
        self.gridlayout5.setMargin(9)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")

        spacerItem2 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout5.addItem(spacerItem2,2,0,1,1)

        self.bntColorDefaults = QtGui.QPushButton(self.tab)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColorDefaults.sizePolicy().hasHeightForWidth())
        self.bntColorDefaults.setSizePolicy(sizePolicy)
        self.bntColorDefaults.setObjectName("bntColorDefaults")
        self.gridlayout5.addWidget(self.bntColorDefaults,1,0,1,1)

        self.frame2_2 = QtGui.QFrame(self.tab)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2_2.sizePolicy().hasHeightForWidth())
        self.frame2_2.setSizePolicy(sizePolicy)
        self.frame2_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2_2.setObjectName("frame2_2")

        self.gridlayout6 = QtGui.QGridLayout(self.frame2_2)
        self.gridlayout6.setMargin(9)
        self.gridlayout6.setSpacing(6)
        self.gridlayout6.setObjectName("gridlayout6")

        self.ColorComment = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorComment.sizePolicy().hasHeightForWidth())
        self.ColorComment.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.ColorComment.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorComment.setFont(font)
        self.ColorComment.setObjectName("ColorComment")
        self.gridlayout6.addWidget(self.ColorComment,3,0,1,1)

        self.bntColorComment = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColorComment.sizePolicy().hasHeightForWidth())
        self.bntColorComment.setSizePolicy(sizePolicy)
        self.bntColorComment.setObjectName("bntColorComment")
        self.gridlayout6.addWidget(self.bntColorComment,3,2,1,1)

        self.bntColorTarget = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColorTarget.sizePolicy().hasHeightForWidth())
        self.bntColorTarget.setSizePolicy(sizePolicy)
        self.bntColorTarget.setObjectName("bntColorTarget")
        self.gridlayout6.addWidget(self.bntColorTarget,2,2,1,1)

        self.bntColorSource = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColorSource.sizePolicy().hasHeightForWidth())
        self.bntColorSource.setSizePolicy(sizePolicy)
        self.bntColorSource.setObjectName("bntColorSource")
        self.gridlayout6.addWidget(self.bntColorSource,1,2,1,1)

        self.bntColorOverview = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColorOverview.sizePolicy().hasHeightForWidth())
        self.bntColorOverview.setSizePolicy(sizePolicy)
        self.bntColorOverview.setObjectName("bntColorOverview")
        self.gridlayout6.addWidget(self.bntColorOverview,0,2,1,1)

        self.ColorTarget = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorTarget.sizePolicy().hasHeightForWidth())
        self.ColorTarget.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.ColorTarget.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorTarget.setFont(font)
        self.ColorTarget.setObjectName("ColorTarget")
        self.gridlayout6.addWidget(self.ColorTarget,2,0,1,1)

        self.ColorOverview = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorOverview.sizePolicy().hasHeightForWidth())
        self.ColorOverview.setSizePolicy(sizePolicy)
        self.ColorOverview.setMaximumSize(QtCore.QSize(16777207,16777215))

        font = QtGui.QFont(self.ColorOverview.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorOverview.setFont(font)
        self.ColorOverview.setScaledContents(True)
        self.ColorOverview.setWordWrap(True)
        self.ColorOverview.setIndent(0)
        self.ColorOverview.setObjectName("ColorOverview")
        self.gridlayout6.addWidget(self.ColorOverview,0,0,1,1)

        self.ColorSource = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorSource.sizePolicy().hasHeightForWidth())
        self.ColorSource.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.ColorSource.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorSource.setFont(font)
        self.ColorSource.setObjectName("ColorSource")
        self.gridlayout6.addWidget(self.ColorSource,1,0,1,1)

        self.tuTargetColor = QtGui.QLineEdit(self.frame2_2)
        self.tuTargetColor.setReadOnly(True)
        self.tuTargetColor.setObjectName("tuTargetColor")
        self.gridlayout6.addWidget(self.tuTargetColor,2,1,1,1)

        self.commentColor = QtGui.QLineEdit(self.frame2_2)
        self.commentColor.setReadOnly(True)
        self.commentColor.setObjectName("commentColor")
        self.gridlayout6.addWidget(self.commentColor,3,1,1,1)

        self.overviewColor = QtGui.QLineEdit(self.frame2_2)
        self.overviewColor.setEnabled(True)
        self.overviewColor.setReadOnly(True)
        self.overviewColor.setObjectName("overviewColor")
        self.gridlayout6.addWidget(self.overviewColor,0,1,1,1)

        self.tuSourceColor = QtGui.QLineEdit(self.frame2_2)

        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(1),QtGui.QColor(221,223,228))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,85))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(5),QtGui.QColor(199,199,199))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(10),QtGui.QColor(239,239,239))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(12),QtGui.QColor(103,141,178))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(1),QtGui.QColor(221,223,228))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,85))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(5),QtGui.QColor(199,199,199))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(10),QtGui.QColor(239,239,239))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(12),QtGui.QColor(103,141,178))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(0),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(1),QtGui.QColor(221,223,228))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,85))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(5),QtGui.QColor(199,199,199))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(6),QtGui.QColor(199,199,199))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(8),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(9),QtGui.QColor(239,239,239))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(10),QtGui.QColor(239,239,239))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(12),QtGui.QColor(86,117,148))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        self.tuSourceColor.setPalette(palette)
        self.tuSourceColor.setReadOnly(True)
        self.tuSourceColor.setObjectName("tuSourceColor")
        self.gridlayout6.addWidget(self.tuSourceColor,1,1,1,1)
        self.gridlayout5.addWidget(self.frame2_2,0,0,1,1)
        self.tabWidget.addTab(self.tab, "")
        self.gridlayout.addWidget(self.tabWidget,0,0,1,1)

        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(5)
        self.hboxlayout.setObjectName("hboxlayout")

        spacerItem3 = QtGui.QSpacerItem(287,31,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem3)

        self.okButton = QtGui.QPushButton(frmPreference)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(1),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)

        self.cancelButton = QtGui.QPushButton(frmPreference)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.gridlayout.addLayout(self.hboxlayout,1,0,1,1)

        self.retranslateUi(frmPreference)
        self.cbxFullLanguage.setCurrentIndex(-1)
        QtCore.QObject.connect(self.cancelButton,QtCore.SIGNAL("clicked()"),frmPreference.reject)
        QtCore.QObject.connect(self.okButton,QtCore.SIGNAL("clicked()"),frmPreference.accept)
        QtCore.QMetaObject.connectSlotsByName(frmPreference)
        frmPreference.setTabOrder(self.UserName,self.EmailAddress)
        frmPreference.setTabOrder(self.EmailAddress,self.cbxFullLanguage)
        frmPreference.setTabOrder(self.cbxFullLanguage,self.cbxLanguageCode)
        frmPreference.setTabOrder(self.cbxLanguageCode,self.SupportTeam)
        frmPreference.setTabOrder(self.SupportTeam,self.cbxTimeZone)
        frmPreference.setTabOrder(self.cbxTimeZone,self.chkHeaderAuto)
        frmPreference.setTabOrder(self.chkHeaderAuto,self.bntOverview)
        frmPreference.setTabOrder(self.bntOverview,self.bntSource)
        frmPreference.setTabOrder(self.bntSource,self.bntTarget)
        frmPreference.setTabOrder(self.bntTarget,self.bntComment)
        frmPreference.setTabOrder(self.bntComment,self.bntDefaults)
        frmPreference.setTabOrder(self.bntDefaults,self.okButton)
        frmPreference.setTabOrder(self.okButton,self.cancelButton)
        frmPreference.setTabOrder(self.cancelButton,self.tabWidget)
        frmPreference.setTabOrder(self.tabWidget,self.frame)

    def tr(self, string):
        return QtGui.QApplication.translate("frmPreference", string, None, QtGui.QApplication.UnicodeUTF8)

    def retranslateUi(self, frmPreference):
        frmPreference.setWindowTitle(self.tr("Preference"))
        self.label5.setText(self.tr("Support team"))
        self.label6.setText(self.tr("Time zone"))
        self.label1.setText(self.tr("User name"))
        self.label3.setText(self.tr("Full language name"))
        self.label2.setText(self.tr("Email address"))
        self.label4.setText(self.tr("Language Code"))
        self.chkHeaderAuto.setText(self.tr("Automatically update header on save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), self.tr("Personalize"))
        self.bntDefaults.setText(self.tr("Defaults"))
        self.Source.setText(self.tr("Source"))
        self.bntComment.setText(self.tr("Choose"))
        self.bntTarget.setText(self.tr("Choose"))
        self.bntSource.setText(self.tr("Choose"))
        self.lblsupportteam.setText(self.tr("Comment"))
        self.label41.setText(self.tr("Target"))
        self.bntOverview.setText(self.tr("Choose"))
        self.label21.setText(self.tr("Overview"))
        self.label2_2.setText(self.tr("Overview header"))
        self.bntOverviewHeader.setText(self.tr("Choose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), self.tr("Font"))
        self.bntColorDefaults.setText(self.tr("Defaults"))
        self.ColorComment.setText(self.tr("Comment"))
        self.bntColorComment.setText(self.tr("Choose"))
        self.bntColorTarget.setText(self.tr("Choose"))
        self.bntColorSource.setText(self.tr("Choose"))
        self.bntColorOverview.setText(self.tr("Choose"))
        self.ColorTarget.setText(self.tr("Target"))
        self.ColorOverview.setText(self.tr("Overview"))
        self.ColorSource.setText(self.tr("Source"))
        self.tuTargetColor.setText(self.tr("Sample text"))
        self.commentColor.setText(self.tr("Sample text"))
        self.overviewColor.setText(self.tr("Sample text"))
        self.tuSourceColor.setText(self.tr("Sample text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), self.tr("Color"))
        self.okButton.setText(self.tr("OK"))
        self.cancelButton.setText(self.tr("Cancel"))


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    frmPreference = QtGui.QDialog()
    ui = Ui_frmPreference()
    ui.setupUi(frmPreference)
    frmPreference.show()
    sys.exit(app.exec_())
