# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unknown'
#
# Created: Tue Feb 20 09:41:44 2007
#      by: PyQt4 UI code generator 4.0
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt4 import QtCore, QtGui

class Ui_frmPreference(object):
    def setupUi(self, frmPreference):
        frmPreference.setObjectName("frmPreference")
        frmPreference.resize(QtCore.QSize(QtCore.QRect(0,0,516,386).size()).expandedTo(frmPreference.minimumSizeHint()))

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPreference.sizePolicy().hasHeightForWidth())
        frmPreference.setSizePolicy(sizePolicy)

        self.gridlayout = QtGui.QGridLayout(frmPreference)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")

        self.tabWidget = QtGui.QTabWidget(frmPreference)
        self.tabWidget.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.tabWidget.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")

        self.tab1 = QtGui.QWidget()
        self.tab1.setEnabled(True)
        self.tab1.setObjectName("tab1")

        self.gridlayout1 = QtGui.QGridLayout(self.tab1)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")

        self.frame_2 = QtGui.QFrame(self.tab1)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.hboxlayout = QtGui.QHBoxLayout(self.frame_2)
        self.hboxlayout.setMargin(9)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")

        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)

        self.spinBox = QtGui.QSpinBox(self.frame_2)
        self.spinBox.setObjectName("spinBox")
        self.hboxlayout.addWidget(self.spinBox)
        self.gridlayout1.addWidget(self.frame_2,1,0,1,1)

        spacerItem = QtGui.QSpacerItem(20,41,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem,3,0,1,1)

        self.chkHeaderAuto = QtGui.QCheckBox(self.tab1)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkHeaderAuto.sizePolicy().hasHeightForWidth())
        self.chkHeaderAuto.setSizePolicy(sizePolicy)
        self.chkHeaderAuto.setChecked(True)
        self.chkHeaderAuto.setObjectName("chkHeaderAuto")
        self.gridlayout1.addWidget(self.chkHeaderAuto,2,0,1,1)

        self.frame = QtGui.QFrame(self.tab1)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.gridlayout2 = QtGui.QGridLayout(self.frame)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")

        self.label5 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setObjectName("label5")
        self.gridlayout2.addWidget(self.label5,3,0,1,1)

        self.cbxLanguageCode = QtGui.QComboBox(self.frame)
        self.cbxLanguageCode.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxLanguageCode.sizePolicy().hasHeightForWidth())
        self.cbxLanguageCode.setSizePolicy(sizePolicy)
        self.cbxLanguageCode.setAcceptDrops(False)
        self.cbxLanguageCode.setEditable(True)
        self.cbxLanguageCode.setObjectName("cbxLanguageCode")
        self.gridlayout2.addWidget(self.cbxLanguageCode,2,3,1,1)

        self.label6 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6.sizePolicy().hasHeightForWidth())
        self.label6.setSizePolicy(sizePolicy)
        self.label6.setObjectName("label6")
        self.gridlayout2.addWidget(self.label6,4,0,1,1)

        self.cbxFullLanguage = QtGui.QComboBox(self.frame)
        self.cbxFullLanguage.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxFullLanguage.sizePolicy().hasHeightForWidth())
        self.cbxFullLanguage.setSizePolicy(sizePolicy)
        self.cbxFullLanguage.setEditable(True)
        self.cbxFullLanguage.setObjectName("cbxFullLanguage")
        self.gridlayout2.addWidget(self.cbxFullLanguage,2,1,1,1)

        self.cbxTimeZone = QtGui.QComboBox(self.frame)
        self.cbxTimeZone.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxTimeZone.sizePolicy().hasHeightForWidth())
        self.cbxTimeZone.setSizePolicy(sizePolicy)
        self.cbxTimeZone.setEditable(True)
        self.cbxTimeZone.setObjectName("cbxTimeZone")
        self.gridlayout2.addWidget(self.cbxTimeZone,4,1,1,3)

        self.label1 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setObjectName("label1")
        self.gridlayout2.addWidget(self.label1,0,0,1,1)

        self.label3 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setObjectName("label3")
        self.gridlayout2.addWidget(self.label3,2,0,1,1)

        self.label2 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setObjectName("label2")
        self.gridlayout2.addWidget(self.label2,1,0,1,1)

        self.label4 = QtGui.QLabel(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4.sizePolicy().hasHeightForWidth())
        self.label4.setSizePolicy(sizePolicy)
        self.label4.setObjectName("label4")
        self.gridlayout2.addWidget(self.label4,2,2,1,1)

        self.UserName = QtGui.QLineEdit(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserName.sizePolicy().hasHeightForWidth())
        self.UserName.setSizePolicy(sizePolicy)
        self.UserName.setMaxLength(32768)
        self.UserName.setObjectName("UserName")
        self.gridlayout2.addWidget(self.UserName,0,1,1,3)

        self.EmailAddress = QtGui.QLineEdit(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmailAddress.sizePolicy().hasHeightForWidth())
        self.EmailAddress.setSizePolicy(sizePolicy)
        self.EmailAddress.setObjectName("EmailAddress")
        self.gridlayout2.addWidget(self.EmailAddress,1,1,1,3)

        self.SupportTeam = QtGui.QLineEdit(self.frame)
        self.SupportTeam.setObjectName("SupportTeam")
        self.gridlayout2.addWidget(self.SupportTeam,3,1,1,3)
        self.gridlayout1.addWidget(self.frame,0,0,1,1)
        self.tabWidget.addTab(self.tab1, "")

        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")

        self.gridlayout3 = QtGui.QGridLayout(self.tab2)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")

        self.frame2 = QtGui.QFrame(self.tab2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2.setObjectName("frame2")

        self.gridlayout4 = QtGui.QGridLayout(self.frame2)
        self.gridlayout4.setMargin(9)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")

        self.label2_2 = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_2.sizePolicy().hasHeightForWidth())
        self.label2_2.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label2_2.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label2_2.setFont(font)
        self.label2_2.setScaledContents(True)
        self.label2_2.setWordWrap(True)
        self.label2_2.setIndent(0)
        self.label2_2.setObjectName("label2_2")
        self.gridlayout4.addWidget(self.label2_2,0,0,1,1)

        self.bntFontOverviewHeader = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntFontOverviewHeader.sizePolicy().hasHeightForWidth())
        self.bntFontOverviewHeader.setSizePolicy(sizePolicy)
        self.bntFontOverviewHeader.setObjectName("bntFontOverviewHeader")
        self.gridlayout4.addWidget(self.bntFontOverviewHeader,0,2,1,1)

        self.lblOverViewHeader = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOverViewHeader.sizePolicy().hasHeightForWidth())
        self.lblOverViewHeader.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblOverViewHeader.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblOverViewHeader.setFont(font)
        self.lblOverViewHeader.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOverViewHeader.setObjectName("lblOverViewHeader")
        self.gridlayout4.addWidget(self.lblOverViewHeader,0,1,1,1)

        self.btnColorOverview = QtGui.QPushButton(self.frame2)
        self.btnColorOverview.setObjectName("btnColorOverview")
        self.gridlayout4.addWidget(self.btnColorOverview,1,3,1,1)

        self.bntFontOverview = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntFontOverview.sizePolicy().hasHeightForWidth())
        self.bntFontOverview.setSizePolicy(sizePolicy)
        self.bntFontOverview.setObjectName("bntFontOverview")
        self.gridlayout4.addWidget(self.bntFontOverview,1,2,1,1)

        self.lblOverView = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOverView.sizePolicy().hasHeightForWidth())
        self.lblOverView.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblOverView.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblOverView.setFont(font)
        self.lblOverView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOverView.setObjectName("lblOverView")
        self.gridlayout4.addWidget(self.lblOverView,1,1,1,1)

        self.label2_3 = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_3.sizePolicy().hasHeightForWidth())
        self.label2_3.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label2_3.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label2_3.setFont(font)
        self.label2_3.setScaledContents(True)
        self.label2_3.setWordWrap(True)
        self.label2_3.setIndent(0)
        self.label2_3.setObjectName("label2_3")
        self.gridlayout4.addWidget(self.label2_3,1,0,1,1)

        self.bntFontTarget = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntFontTarget.sizePolicy().hasHeightForWidth())
        self.bntFontTarget.setSizePolicy(sizePolicy)
        self.bntFontTarget.setObjectName("bntFontTarget")
        self.gridlayout4.addWidget(self.bntFontTarget,3,2,1,1)

        self.lblComment = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblComment.sizePolicy().hasHeightForWidth())
        self.lblComment.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblComment.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblComment.setFont(font)
        self.lblComment.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblComment.setObjectName("lblComment")
        self.gridlayout4.addWidget(self.lblComment,4,1,1,1)

        self.lblTarget = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTarget.sizePolicy().hasHeightForWidth())
        self.lblTarget.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblTarget.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblTarget.setFont(font)
        self.lblTarget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTarget.setObjectName("lblTarget")
        self.gridlayout4.addWidget(self.lblTarget,3,1,1,1)

        self.lblSource = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSource.sizePolicy().hasHeightForWidth())
        self.lblSource.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblSource.font())
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblSource.setFont(font)
        self.lblSource.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSource.setObjectName("lblSource")
        self.gridlayout4.addWidget(self.lblSource,2,1,1,1)

        self.Source = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Source.sizePolicy().hasHeightForWidth())
        self.Source.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.Source.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.Source.setFont(font)
        self.Source.setObjectName("Source")
        self.gridlayout4.addWidget(self.Source,2,0,1,1)

        self.bntFontSource = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntFontSource.sizePolicy().hasHeightForWidth())
        self.bntFontSource.setSizePolicy(sizePolicy)
        self.bntFontSource.setObjectName("bntFontSource")
        self.gridlayout4.addWidget(self.bntFontSource,2,2,1,1)

        self.lblsupportteam = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblsupportteam.sizePolicy().hasHeightForWidth())
        self.lblsupportteam.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.lblsupportteam.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lblsupportteam.setFont(font)
        self.lblsupportteam.setObjectName("lblsupportteam")
        self.gridlayout4.addWidget(self.lblsupportteam,4,0,1,1)

        self.bntFontComment = QtGui.QPushButton(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntFontComment.sizePolicy().hasHeightForWidth())
        self.bntFontComment.setSizePolicy(sizePolicy)
        self.bntFontComment.setObjectName("bntFontComment")
        self.gridlayout4.addWidget(self.bntFontComment,4,2,1,1)

        self.label4_2 = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_2.sizePolicy().hasHeightForWidth())
        self.label4_2.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label4_2.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label4_2.setFont(font)
        self.label4_2.setObjectName("label4_2")
        self.gridlayout4.addWidget(self.label4_2,3,0,1,1)

        self.btnColorSource = QtGui.QPushButton(self.frame2)
        self.btnColorSource.setObjectName("btnColorSource")
        self.gridlayout4.addWidget(self.btnColorSource,2,3,1,1)

        self.btnColorTarget = QtGui.QPushButton(self.frame2)
        self.btnColorTarget.setObjectName("btnColorTarget")
        self.gridlayout4.addWidget(self.btnColorTarget,3,3,1,1)

        self.btnColorComment = QtGui.QPushButton(self.frame2)
        self.btnColorComment.setObjectName("btnColorComment")
        self.gridlayout4.addWidget(self.btnColorComment,4,3,1,1)
        self.gridlayout3.addWidget(self.frame2,0,0,1,3)

        self.bntDefaultsFont = QtGui.QPushButton(self.tab2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntDefaultsFont.sizePolicy().hasHeightForWidth())
        self.bntDefaultsFont.setSizePolicy(sizePolicy)
        self.bntDefaultsFont.setObjectName("bntDefaultsFont")
        self.gridlayout3.addWidget(self.bntDefaultsFont,1,1,1,1)

        self.bntDefaultsColor = QtGui.QPushButton(self.tab2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntDefaultsColor.sizePolicy().hasHeightForWidth())
        self.bntDefaultsColor.setSizePolicy(sizePolicy)
        self.bntDefaultsColor.setObjectName("bntDefaultsColor")
        self.gridlayout3.addWidget(self.bntDefaultsColor,1,2,1,1)

        spacerItem1 = QtGui.QSpacerItem(20,51,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem1,2,0,1,1)
        self.tabWidget.addTab(self.tab2, "")

        self.tab = QtGui.QWidget()
        self.tab.setEnabled(False)
        self.tab.setObjectName("tab")

        self.gridlayout5 = QtGui.QGridLayout(self.tab)
        self.gridlayout5.setMargin(9)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")

        spacerItem2 = QtGui.QSpacerItem(221,61,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout5.addItem(spacerItem2,2,1,1,1)

        self.frame2_2 = QtGui.QFrame(self.tab)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2_2.sizePolicy().hasHeightForWidth())
        self.frame2_2.setSizePolicy(sizePolicy)
        self.frame2_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2_2.setObjectName("frame2_2")

        self.gridlayout6 = QtGui.QGridLayout(self.frame2_2)
        self.gridlayout6.setMargin(9)
        self.gridlayout6.setSpacing(6)
        self.gridlayout6.setObjectName("gridlayout6")

        self.bntColor = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColor.sizePolicy().hasHeightForWidth())
        self.bntColor.setSizePolicy(sizePolicy)
        self.bntColor.setObjectName("bntColor")
        self.gridlayout6.addWidget(self.bntColor,3,2,1,1)

        self.bntColor1 = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColor1.sizePolicy().hasHeightForWidth())
        self.bntColor1.setSizePolicy(sizePolicy)
        self.bntColor1.setObjectName("bntColor1")
        self.gridlayout6.addWidget(self.bntColor1,4,2,1,1)

        self.bntColor2 = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColor2.sizePolicy().hasHeightForWidth())
        self.bntColor2.setSizePolicy(sizePolicy)
        self.bntColor2.setObjectName("bntColor2")
        self.gridlayout6.addWidget(self.bntColor2,2,2,1,1)

        self.overviewColor = QtGui.QLineEdit(self.frame2_2)
        self.overviewColor.setEnabled(False)
        self.overviewColor.setReadOnly(True)
        self.overviewColor.setObjectName("overviewColor")
        self.gridlayout6.addWidget(self.overviewColor,0,1,1,1)

        self.tuSourceColor = QtGui.QLineEdit(self.frame2_2)

        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(1),QtGui.QColor(221,223,228))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,85))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(5),QtGui.QColor(199,199,199))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(10),QtGui.QColor(239,239,239))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(12),QtGui.QColor(103,141,178))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(1),QtGui.QColor(221,223,228))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,85))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(5),QtGui.QColor(199,199,199))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(10),QtGui.QColor(239,239,239))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(12),QtGui.QColor(103,141,178))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(0),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(1),QtGui.QColor(221,223,228))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,85))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(5),QtGui.QColor(199,199,199))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(6),QtGui.QColor(199,199,199))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(8),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(9),QtGui.QColor(239,239,239))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(10),QtGui.QColor(239,239,239))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(12),QtGui.QColor(86,117,148))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        self.tuSourceColor.setPalette(palette)
        self.tuSourceColor.setReadOnly(True)
        self.tuSourceColor.setObjectName("tuSourceColor")
        self.gridlayout6.addWidget(self.tuSourceColor,1,1,1,1)

        self.tuTargetColor = QtGui.QLineEdit(self.frame2_2)
        self.tuTargetColor.setReadOnly(True)
        self.tuTargetColor.setObjectName("tuTargetColor")
        self.gridlayout6.addWidget(self.tuTargetColor,2,1,1,1)

        self.commentColor = QtGui.QLineEdit(self.frame2_2)
        self.commentColor.setReadOnly(True)
        self.commentColor.setObjectName("commentColor")
        self.gridlayout6.addWidget(self.commentColor,3,1,1,1)

        self.ColorTags = QtGui.QLineEdit(self.frame2_2)
        self.ColorTags.setReadOnly(True)
        self.ColorTags.setObjectName("ColorTags")
        self.gridlayout6.addWidget(self.ColorTags,4,1,1,1)

        self.ColorComment = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorComment.sizePolicy().hasHeightForWidth())
        self.ColorComment.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.ColorComment.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorComment.setFont(font)
        self.ColorComment.setObjectName("ColorComment")
        self.gridlayout6.addWidget(self.ColorComment,3,0,1,1)

        self.ColorTarget = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorTarget.sizePolicy().hasHeightForWidth())
        self.ColorTarget.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.ColorTarget.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorTarget.setFont(font)
        self.ColorTarget.setObjectName("ColorTarget")
        self.gridlayout6.addWidget(self.ColorTarget,2,0,1,1)

        self.ColorSource = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorSource.sizePolicy().hasHeightForWidth())
        self.ColorSource.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.ColorSource.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorSource.setFont(font)
        self.ColorSource.setObjectName("ColorSource")
        self.gridlayout6.addWidget(self.ColorSource,1,0,1,1)

        self.ColorOverview = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorOverview.sizePolicy().hasHeightForWidth())
        self.ColorOverview.setSizePolicy(sizePolicy)
        self.ColorOverview.setMaximumSize(QtCore.QSize(16777207,16777215))

        font = QtGui.QFont(self.ColorOverview.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorOverview.setFont(font)
        self.ColorOverview.setScaledContents(True)
        self.ColorOverview.setWordWrap(True)
        self.ColorOverview.setIndent(0)
        self.ColorOverview.setObjectName("ColorOverview")
        self.gridlayout6.addWidget(self.ColorOverview,0,0,1,1)

        self.ColorTags1 = QtGui.QLabel(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorTags1.sizePolicy().hasHeightForWidth())
        self.ColorTags1.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.ColorTags1.font())
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ColorTags1.setFont(font)
        self.ColorTags1.setObjectName("ColorTags1")
        self.gridlayout6.addWidget(self.ColorTags1,4,0,1,1)

        self.bntColor3 = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColor3.sizePolicy().hasHeightForWidth())
        self.bntColor3.setSizePolicy(sizePolicy)
        self.bntColor3.setObjectName("bntColor3")
        self.gridlayout6.addWidget(self.bntColor3,1,2,1,1)

        self.bntColor4 = QtGui.QPushButton(self.frame2_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColor4.sizePolicy().hasHeightForWidth())
        self.bntColor4.setSizePolicy(sizePolicy)
        self.bntColor4.setObjectName("bntColor4")
        self.gridlayout6.addWidget(self.bntColor4,0,2,1,1)
        self.gridlayout5.addWidget(self.frame2_2,0,0,1,2)

        self.bntColorDefaults = QtGui.QPushButton(self.tab)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bntColorDefaults.sizePolicy().hasHeightForWidth())
        self.bntColorDefaults.setSizePolicy(sizePolicy)
        self.bntColorDefaults.setObjectName("bntColorDefaults")
        self.gridlayout5.addWidget(self.bntColorDefaults,1,0,1,1)
        self.tabWidget.addTab(self.tab, "")
        self.gridlayout.addWidget(self.tabWidget,0,0,1,1)

        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(5)
        self.hboxlayout1.setObjectName("hboxlayout1")

        spacerItem3 = QtGui.QSpacerItem(287,31,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem3)

        self.okButton = QtGui.QPushButton(frmPreference)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(1),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName("okButton")
        self.hboxlayout1.addWidget(self.okButton)

        self.cancelButton = QtGui.QPushButton(frmPreference)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout1.addWidget(self.cancelButton)
        self.gridlayout.addLayout(self.hboxlayout1,1,0,1,1)

        self.retranslateUi(frmPreference)
        self.tabWidget.setCurrentIndex(0)
        self.cbxFullLanguage.setCurrentIndex(-1)
        QtCore.QObject.connect(self.cancelButton,QtCore.SIGNAL("clicked()"),frmPreference.reject)
        QtCore.QObject.connect(self.okButton,QtCore.SIGNAL("clicked()"),frmPreference.accept)
        QtCore.QMetaObject.connectSlotsByName(frmPreference)
        frmPreference.setTabOrder(self.UserName,self.EmailAddress)
        frmPreference.setTabOrder(self.EmailAddress,self.cbxFullLanguage)
        frmPreference.setTabOrder(self.cbxFullLanguage,self.cbxLanguageCode)
        frmPreference.setTabOrder(self.cbxLanguageCode,self.SupportTeam)
        frmPreference.setTabOrder(self.SupportTeam,self.cbxTimeZone)
        frmPreference.setTabOrder(self.cbxTimeZone,self.okButton)
        frmPreference.setTabOrder(self.okButton,self.cancelButton)
        frmPreference.setTabOrder(self.cancelButton,self.tabWidget)
        frmPreference.setTabOrder(self.tabWidget,self.frame)

    def tr(self, string):
        return QtGui.QApplication.translate("frmPreference", string, None, QtGui.QApplication.UnicodeUTF8)

    def retranslateUi(self, frmPreference):
        frmPreference.setWindowTitle(self.tr("Preference"))
        self.label.setText(self.tr("Number of single/plural form:"))
        self.chkHeaderAuto.setText(self.tr("Automatically update header on save"))
        self.label5.setText(self.tr("Support team"))
        self.label6.setText(self.tr("Time zone"))
        self.label1.setText(self.tr("User name"))
        self.label3.setText(self.tr("Full language name"))
        self.label2.setText(self.tr("Email address"))
        self.label4.setText(self.tr("Language Code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), self.tr("Personalize"))
        self.label2_2.setText(self.tr("Overview header"))
        self.bntFontOverviewHeader.setText(self.tr("Font"))
        self.btnColorOverview.setText(self.tr("Color"))
        self.bntFontOverview.setText(self.tr("Font"))
        self.label2_3.setText(self.tr("Overview"))
        self.bntFontTarget.setText(self.tr("Font"))
        self.Source.setText(self.tr("Source"))
        self.bntFontSource.setText(self.tr("Font"))
        self.lblsupportteam.setText(self.tr("Comment"))
        self.bntFontComment.setText(self.tr("Font"))
        self.label4_2.setText(self.tr("Target"))
        self.btnColorSource.setText(self.tr("Color"))
        self.btnColorTarget.setText(self.tr("Color"))
        self.btnColorComment.setText(self.tr("Color"))
        self.bntDefaultsFont.setText(self.tr("Defaults Font"))
        self.bntDefaultsColor.setText(self.tr("Defaults Color"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), self.tr("Settings"))
        self.bntColor.setText(self.tr("Choose"))
        self.bntColor1.setText(self.tr("Choose"))
        self.bntColor2.setText(self.tr("Choose"))
        self.overviewColor.setText(self.tr("Sample text"))
        self.tuSourceColor.setText(self.tr("Sample text"))
        self.tuTargetColor.setText(self.tr("Sample text"))
        self.commentColor.setText(self.tr("Sample text"))
        self.ColorTags.setText(self.tr("Sample text"))
        self.ColorComment.setText(self.tr("Comment"))
        self.ColorTarget.setText(self.tr("Target"))
        self.ColorSource.setText(self.tr("Source"))
        self.ColorOverview.setText(self.tr("Overview"))
        self.ColorTags1.setText(self.tr("For Tags"))
        self.bntColor3.setText(self.tr("Choose"))
        self.bntColor4.setText(self.tr("Choose"))
        self.bntColorDefaults.setText(self.tr("Defaults"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), self.tr("Colorize Tags"))
        self.okButton.setText(self.tr("OK"))
        self.cancelButton.setText(self.tr("Cancel"))


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    frmPreference = QtGui.QDialog()
    ui = Ui_frmPreference()
    ui.setupUi(frmPreference)
    frmPreference.show()
    sys.exit(app.exec_())
