#!/usr/bin/env python
# 
# Copyright 2015 Zuza Software Foundation
# Copyright 2015 Sarah Hale (sjhale892@gmail.com)
# 
# This file is part of translate.
#
# translate is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

"""simple script to convert a Gettext PO localisation file to a
.Net Resource (.resx) file"""

from translate.convert import po2resx

if __name__ == '__main__':
    po2resx.main()

