#!/bin/bash

enpodir=en-po
gsidir=.gsi
user_agent="Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9b5) Gecko/2008032620 Firefox/3.0b5"

mkdir -p $gsidir

which oo2po
if [ $? -ne 0 ]; then
	echo "Please install oo2po and friends"
	exit 1
fi

cd $gsidir

# Get files from Pavel
if [ "$1" != "--no-download" ]; then
	echo "Downloading files:"
	#wget -N --user-agent="$user_agent" --retr-symlinks ftp://ftp.linux.cz/pub/localization/OpenOffice.org/devel/POT/OpenOffice.org-POT-stable-latest.tar.gz
	#wget -N --user-agent="$user_agent" --retr-symlinks ftp://ftp.linux.cz/pub/localization/OpenOffice.org/devel/POT/OpenOffice.org-POT-latest.tar.gz
	curl --remote-time --remote-name ftp://ftp.linux.cz/pub/localization/OpenOffice.org/devel/POT/OpenOffice.org-POT-stable-latest.tar.gz 
	curl --remote-time --remote-name ftp://ftp.linux.cz/pub/localization/OpenOffice.org/devel/POT/OpenOffice.org-POT-latest.tar.gz 
fi

for gsi in $(ls OpenOffice.org*POT*.tar.gz)
do
        echo "### Checking $gsi ###"
        echo "Untarring"
	tar xzf $gsi || break
	rm -rf pot

        potdir=$(echo $gsi | sed "s/\.tar\.gz//").pot
	echo "Convert GSI to POT:"
        mkdir -p $potdir
	oo2po -P en-US.sdf $potdir
	
        enpodir=$(echo $gsi | sed "s/\.tar\.gz//").en.po
	echo "Create English version using poen:"
        rm -rf $enpodir
        mkdir -p $enpodir
	podebug -f "" --rewrite=en $potdir $enpodir
	
        targetsdf=$(echo $gsi | sed "s/\.tar\.gz//").sdf
	echo "Create $targetsdf:"
	po2oo -l en-XX -t en-US.sdf $enpodir $targetsdf
	
	# Check for lines that are not duplicated
	echo "Analysing (you should see nothing between START and END, anything else is a roundtrip issue):"
        echo "---START---"
	cut -f11,13,14 $targetsdf | uniq -u
        echo "----END----"
done

rm -rf $potdir $enpodir
