User's Guide
------------

This part has the user's documentation for the tools included in the
Translate Toolkit.

.. toctree::
   :maxdepth: 2

   installation
   converters
   scripts


Developer's Guide
-----------------

If you are a developer and are willing to use the Translate Toolkit for
building new tools, make sure to read through this part.

.. toctree::
   :maxdepth: 2

   styleguide


API Reference
-------------

This part covers any function, class or method included within the
Translate Toolkit that you can use to programatically build new
localization tools.

.. toctree::
   :maxdepth: 2

   api/index


Additional Notes
----------------

Changelog and legal information are included here.

.. toctree::
   :maxdepth: 2

   changelog
   license
