name: Pre-commit check

on:
  push:
    branches-ignore:
    - renovate/**
    - dependabot/**
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.cache/prek
        key: ${{ runner.os }}-prek-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-prek-
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: 0.11.8
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.14
    - name: prek
      run: uv run --no-sources --only-group pre-commit prek run --all-files
      env:
        RUFF_OUTPUT_FORMAT: github
        REUSE_OUTPUT_FORMAT: github
    - name: diff
      run: git diff
      if: always()
    - name: prek-prune
      run: uv run --no-sources --only-group pre-commit prek cache gc
