name: Pre-commit check

on:
  push:
    branches-ignore:
    - renovate/**
    - dependabot/**
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      with:
        path: ~/.cache/prek
        key: ${{ runner.os }}-prek-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-prek-
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        version: 0.11.23
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.14
    - name: prek
      run: uv run --no-sources --only-group pre-commit prek run --all-files
      env:
        RUFF_OUTPUT_FORMAT: github
        REUSE_OUTPUT_FORMAT: github
    - name: diff
      run: git diff
      if: always()
    - name: prek-prune
      run: uv run --no-sources --only-group pre-commit prek cache gc
